name:                hie-bug
version:             0.1.0.0
github:              "jchia/hie-bug"
license:             BSD3
author:              "Josh Chia"
maintainer:          "joshchia@gmail.com"
copyright:           "Copyright (c) 2017 Joshua Chia"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Demonstrate HIE bug
category:            test

description:         HIE shows an error message when editing Lib2.hs in vscode

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
